### PR TITLE
Integrate other models and fix bugs

### LINKED ISSUE #4: `delete` not implemented
Statement `delete` to be implemented

### LINKED ISSUE #6: Not considering the condition in `symbol_int_c`
Possible problems related with `symbol_int_c` (for instance, associated with the test `large_arrays_pass/c_array_c_write_s_read/10000_0` - I think that it does not take into consideration the condition of the symbolic value `j`)

### PR DESCRIPTION
**Pull request by julianayang777**
- Integrate other models: `HeapTree`, `HeapArrayITE` and `HeapOpLists`
- Fix #6 and fix #4 
- Refactor the way of testing

### CODE REVIEW

File: lib/HeapArrayFork.ml [hunk 1]
```diff
@@ -76,7 +76,7 @@ module M : Heap_intf.M with type vt = Term.t = struct
           (fun index' _ ->
             (* can be optimized *)
             let e = Binop (Equals, index, Val (Integer index')) in
-            if Translator.is_sat ([ e ] @ path) then true else false)
+            Translator.is_sat ([ e ] @ path))
```
Comment (filipeom) [inline lib/HeapArrayFork.ml:78]:
```suggestion
            Translator.is_sat (e :: path))
```
Use cons instead of concat

File: lib/HeapArrayITE.ml [hunk 2]
```diff
@@ -37,6 +37,8 @@ module M : Heap_intf.M with type vt = Term.t = struct
     | _ ->
         failwith "InternalError: HeapArrayIte.in_bounds, arr must be location"
 
+  let copy (heap : t) : t = let heap', i = heap in (Hashtbl.copy heap', i)
```
Comment (filipeom) [inline lib/HeapArrayITE.ml]:
```suggestion
  let copy ((heap, i) : t) : t = (Hashtbl.copy heap, i)
```

Destruct in args

File: lib/HeapArrayITE.ml [hunk 3]
```diff
@@ -103,13 +105,15 @@ module M : Heap_intf.M with type vt = Term.t = struct
...
+                (* Printf.printf "Index: %s\n" (Term.to_string index);
+                Printf.printf "Array: %s\n" (String.concat ", " (Array.to_list (Array.map Term.to_string arr))); *)
                 let aux =
                   Array.of_list
                     (List.filteri
                        (fun index' _ ->
                          (* can be optimized *)
                          let e = Binop (Equals, index, Val (Integer index')) in
-                         if Translator.is_sat ([ e ] @ pc) then true else false)
+                         Translator.is_sat ([ e ] @ pc))
```
Comment (filipeom) [inline lib/HeapArrayITE.ml]:
```suggestion
                         Translator.is_sat (e :: pc))
```
I know you didn't change this, but here we can use list cons instead of concat

File: lib/HeapTree.ml [hunk 4]
```diff
@@ -215,6 +215,8 @@ module M : Heap_intf.M with type vt = Term.t = struct
               "InternalError: HeapTree.in_bounds, accessed tree is not in the \
                heap")
     | _ -> failwith "InternalError: HeapTree.in_bounds, arr must be location"
-
-  let clone _ = assert false
+  
+  let copy (heap : t) : t = let heap', i = heap in (Hashtbl.copy heap', i)
```
Comment (filipeom) [inline lib/HeapTree.ml]: You can also destruct the heap tuple in the args as recommended above.

File: lib/interpreter.ml [hunk 5]
```diff
@@ -82,19 +86,42 @@ module Make
...
+        *)
+    
+    (*
+      let/ state = Choice.get in
+        let v = eval state.store e in
+        let/ b = Choice.select v in
+        if b then return cont else Choice.return Outcome.AssumeF   
+    *)
+
+
```
Comment (filipeom) [inline lib/interpreter.ml]: Can we remove these comments? Otherwise, we probably should describe why they are here instead.

File: lib/interpreter.ml [hunk 6]
```diff
@@ -82,19 +86,42 @@ module Make
...
+            concrete execution context"
+      | Some symb_val ->
+        let f_symb_int (s : state) =
+          Store.set s.store x symb_val;
+          let v = eval s.store c in
+          let pc' = add_condition s.pc v in
+          if is_true pc' 
+            then [ ((), SState.{ s with pc = pc' })]
+            else [] in 
+        let/ _ = Choice.lift f_symb_int in
```
Comment (filipeom) [inline lib/interpreter.ml]:
```suggestion
        let/ () = Choice.lift f_symb_int in 
```
Should be unit val

File: lib/interpreter.ml [hunk 7]
```diff
@@ -226,8 +257,25 @@ module Make
...
+              (fun (hp, pc') ->
+                let store', cs' =
+                  if dup then (Store.dup s.store, Callstack.dup s.cs)
+                  else (s.store, s.cs)
+                in
+                ((), SState.{ heap = hp; pc = pc'; store = store'; cs = cs' }))
+                lst
+          | None -> failwith "InternalError: array is not defined"
+        in 
+        let/ _ = Choice.lift f_delete in
```
Comment (filipeom) [inline lib/interpreter.ml]:
```suggestion
        let/ () = Choice.lift f_delete in
```

File: test/script.ml [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+        (fun (out, _) ->
+        Format.printf "Outcome: %s@." (Outcome.to_string out))
+      rets
+    | "sopl" ->
+      let rets = SOPL.interpret program in
+      List.iter
+        (fun (out, _) ->
+        Format.printf "Outcome: %s@." (Outcome.to_string out))
+      rets
+    | _ -> assert false)
```
Comment (filipeom) [inline test/script.ml]:
```suggestion
    let outcomes = 
      match model with
      | "saf" -> SAF.interpret program
      | "saite" -> SAITE.interpret program
      | "st" -> ST.interpret program
      | "sopl" -> SOPL.interpret program
      | _ -> assert false
    in
    List.iter
      (fun (out, _) -> Format.printf "Outcome: %s@." (Outcome.to_string out))
      outcomes
```

Every `interpret` has the same output so we can do something like this

**Review by filipeom — CHANGES_REQUESTED** [review]
Also, can you run `dune fmt` to format the code?

**Review by filipeom — APPROVED** [review]

**Comment by filipeom** [comment]
Looks good to me, can you just try to fix the non-determinism issues with the tests failing in the ubuntu-ci?

If you're busy I can try to fix this later if you want :)

**Comment by julianayang777** [comment]
I can try!
